### ISSUE TITLE
Machine-readable identification of sensitive data to be encrypted?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-crypto#11]
The sensitive data of a payment method is encrypted. It would be great if we could (for W3C specs) come up with a machine-readable way to identify response members that should be encrypted.

**Comment by adrianhopebailie** [comment]
Why does it need to be machine readable? I don't really understand the use case?

**Comment by ianbjacobs** [comment]
Upon further reflection, I don't think this is a real issue so am closing.
