### ISSUE TITLE
Confusion between CEK and JWE Encryption Key

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-crypto#12]
The spec at https://w3c.github.io/webpayments-crypto/ describes the CEK as an RSA public key but this is in fact the JWE Encryption Key (which encrypts the symmetric CEK) for exchange.

**Comment by ianbjacobs** [comment]
@adrianhopebailie, thank you for the review. Could you suggest some concrete replacement text?

**Comment by adrianhopebailie** [comment]
Will do a PR, just capturing issues as I go
